//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kros.TroubleShooterClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kros.TroubleShooterClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikom spustíte automatické vyhľadanie problémov a vykonajú sa opravy.
        /// </summary>
        public static string buttonDesc1 {
            get {
                return ResourceManager.GetString("buttonDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niektoré problémy Troubleshooter nedokáže sám vyhľadať a preto je potrebné zodpovedať na pár otázok.
        /// </summary>
        public static string buttonDesc2 {
            get {
                return ResourceManager.GetString("buttonDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problém bude odoslaný na servis, kde sa ho pokúsia vyriešiť. Je potrebné mať pripojenie na internet.
        /// </summary>
        public static string buttonDesc3 {
            get {
                return ResourceManager.GetString("buttonDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ukončiť Troubleshooter.
        /// </summary>
        public static string buttonDesc4 {
            get {
                return ResourceManager.GetString("buttonDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budú vykonané všetky opravy zobrazené v podrobnom výpise. Kliknite na tlačidlo lupy pre zobrazenie podrobného výpisu..
        /// </summary>
        public static string buttonDesc5 {
            get {
                return ResourceManager.GetString("buttonDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nájsť problémy a vykonať opravu.
        /// </summary>
        public static string buttonMain1 {
            get {
                return ResourceManager.GetString("buttonMain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrať problémovú oblasť a aplikovať opravu.
        /// </summary>
        public static string buttonMain2 {
            get {
                return ResourceManager.GetString("buttonMain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odoslať na servis.
        /// </summary>
        public static string buttonMain3 {
            get {
                return ResourceManager.GetString("buttonMain3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap greenArrow {
            get {
                object obj = ResourceManager.GetObject("greenArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.&quot;.
        /// </summary>
        public static string lorem {
            get {
                return ResourceManager.GetString("lorem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap problem {
            get {
                object obj = ResourceManager.GetObject("problem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap repair {
            get {
                object obj = ResourceManager.GetObject("repair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nástroj sa pokúsi nájsť problémy vo vašom počítači a odstrániť ich. Ak sa problém nepodarí identifikovať automaticky, máte možnosť určiť ho zodpovedaním pár jednoduchých otázok. Ak problém pretrváva, môžete ho nahlásiť v sekcii odoslať na servis..
        /// </summary>
        public static string troubleshoderDesc {
            get {
                return ResourceManager.GetString("troubleshoderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
