//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleshipsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Turns = new HashSet<Turn>();
        }
    
        public long GameId { get; set; }
        public long Winner { get; set; }
        public long Loser { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turn> Turns { get; set; }
        public virtual Player LoserRef { get; set; }
        public virtual Player WinnerRef { get; set; }
    }
}
